### ISSUE TITLE
npm run build Error: data['use'] should NOT have additional properti

### ISSUE THREAD

**Issue by seeker1983** [dulin666/vue-seed#11]
If I try npm run build of clean download, it fails with
    bash-3.2$ npm run build

    > vue-seed@1.0.1 build /web/github/vue-seed
    > node build/build.js

    /web/github/vue-seed/node_modules/extract-text-webpack-plugin/schema/validator.js:11
    		throw new Error(ajv.errorsText());
    		^

    Error: data['use'] should NOT have additional properties
        at validate (/web/github/vue-seed/node_modules/extract-text-webpack-plugin/schema/validator.js:11:9)
        at Function.ExtractTextPlugin.extract (/web/github/vue-seed/node_modules/extract-text-webpack-plugin/index.js:190:3)
        at generateLoaders (/web/github/vue-seed/build/utils.js:31:32)
        at Object.exports.cssLoaders (/web/github/vue-seed/build/utils.js:42:10)
        at Object.<anonymous> (/web/github/vue-seed/build/vue-loader.conf.js:6:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)

The problem seems to have something with extract plugin, cause if I disable it in utils.js:30 changing

      if (options.extract) {
        return ExtractTextPlugin.extract({
          use: sourceLoader,
          fallback: 'vue-style-loader'
        })
      } else {
        return ['vue-style-loader', sourceLoader].join('!')
      }

to 

      if (FALSE && options.extract) {
        return ExtractTextPlugin.extract({
          use: sourceLoader,
          fallback: 'vue-style-loader'
        })
      } else {
        return ['vue-style-loader', sourceLoader].join('!')
      }

to disable extract, build works fine. But this don't seem to be a solution. 
What is the source of problem?

**Comment by edimitchel** [comment]
Hello @seeker1983, this will fix this issue (replace by the corresponding part) :

```
      return ExtractTextPlugin.extract({
        loader: sourceLoader,
        fallbackLoader: 'vue-style-loader'
      })
```

**Comment by edimitchel** [comment]
#12

**Comment by edimitchel** [comment]
New PR to fix #12

**Comment by dulin666** [comment]
Hey @edimitchel, thanks for contributing and solving the issue.

**Comment by seeker1983** [comment]
Michael, thanks for your reply. Your solution works if I remove the fallbackLoader line from it, like this

	return ExtractTextPlugin.extract({
	  loader: sourceLoader
	})

Gives "data['fallback'] should NOT have additional properties" error if I leave fallbackLoader option
